services:
  postgres:
    image: postgres:16
    container_name: bridge-bank-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bridge_bank_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: bridge-bank-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: