
spring:
  application:
    name: bridge-bank-reserve-once-worker
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bridge_bank_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >-
          reserveTransferResultEvent:bridge.bridge_bank.domain.transfer_transaction_result.event.ReserveTransferResultEvent
      acks: all
      retries: 3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081
